<<<<<<< .mine
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.11 at 04:49:02 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cosic.be/eidtoolset/eidlibrary")
package be.cosic.eidtoolset.eidlibrary;
=======
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.12 at 04:01:24 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cosic.be/eidtoolset/eidlibrary")
package be.cosic.eidtoolset.eidlibrary;
>>>>>>> .r67
